gpu_id: 1
seed: 42
### Roots
train_root: "/home/yiqing/data/crc/NCT-CRC-HE-100K-NONORM"
# train_root: "/home/yiqing/data/crc/NCT-CRC-HE-100K"
test_root: "/home/yiqing/data/crc/CRC-VAL-HE-7K"
output_path: "/home/yiqing/stain/result/" 
postfix: 'NONORM_woPretrain'
### Model
model: "resnet18" # model_name in Timm
pretrained: False # If to use the ImageNet pretrained weights
prenorm: False # If to use the prenorm scheme
### Training Configurations
num_workers: 8
batch_size: 256
learning_rate: 5.0e-4
weight_decay: 1.0e-5
min_learning_rate: 5.0e-6
T_max: 10
gamma: 0.8
epochs: 100
patience: 8
scheduler: 'cosine' 